drop table if exists personal_finance.my_finances.categories;

create table personal_finance.my_finances.categories
as
select
    master.type,
    master.date,
    master.amount,
    master.description,
    master.individual,
    master.month,
    master.year,
    master.day,
    master.flow,

    case
        when
            UPPER(master.description) like '%PAYROLL%'
            then 'Salary'
        when
            UPPER(master.description) like '%AWS.AMAZON.CO%'
            or UPPER(master.description) like '%SPOTIFY%'
            or UPPER(master.description) like '%PRIME VIDEO%'
            or UPPER(master.description) like '%APPLE.COM/BILL%'
            or UPPER(master.description) like '%PRIME VIDEO%'
            or (
                UPPER(master.description) like '%GOOGLE%'
                and UPPER(master.description) not like '%FIBER%'
            )
            then 'Software Services'
        when
            UPPER(master.description) like '%VENMO%'
            or UPPER(master.description) like '%APPLE CASH%'
            then 'Cash Apps'
        when
            UPPER(master.description) like '%QUESTAR%'
            or UPPER(master.description) like '%NESTEGG%'
            or UPPER(master.description) like '%ZELLE%'
            OR UPPER(master.description) = 'RENT'
            then 'Utilities'
        when
            UPPER(master.description) like '%FIBER%'
            or UPPER(master.description) like '%INTERNET%'
            then 'Internet/Cell Services'
        when
            UPPER(master.description) like '%ONLINE TRANSFER%'
            or UPPER(master.description) like '%DEPOSIT%'
            or UPPER(master.description) like '%TAX%'
            or UPPER(master.description) like '%REIMBURSED%'
            or UPPER(master.description) like '%WITHDRAWAL%'
            or UPPER(master.description) like '%ONLINE PAYMENT%'
            or UPPER(master.description) like '%PAYMENT THANK YOU%'
            or UPPER(master.description) like '%AUTOPAY%'
            or UPPER(master.description) like '%INTEREST PAYMENT%'
            or UPPER(master.description) like '%TPG PRODUCTS%'
            or UPPER(master.description) like '%ATM TRANSACTION%'
            then 'Transfers'
        when
            UPPER(master.description) like '%COSTCO WHSE%'
            or UPPER(master.description) like '%MACEYS%'
            or UPPER(master.description) like '%SMITHS%'
            or UPPER(master.description) like '%WALMART%'
            or UPPER(master.description) like '%WAL-MART%'
            or UPPER(master.description) like '%HARMONS%'
            or UPPER(master.description) like '%TIME TRAVELER%'
            or UPPER(master.description) like '%SUPERCENTER%'
            or UPPER(master.description) like '%COSTCO CASH REWARD%'
            or UPPER(master.description) like '%COSTCO ANNUAL MEMBERSHIP%'
            or UPPER(master.description) like '%SAFEWAY%'
            or UPPER(master.description) like '%CIRCLE K%'
            then 'Groceries'
        when
            UPPER(master.description) like '%CHICK-FIL-A%'
            or UPPER(master.description) like '%CRUMBL%'
            or UPPER(master.description) like '%TAMASHI%'
            or UPPER(master.description) like '%FILLINGS & EMULSIONS%'
            or UPPER(master.description) like '%WENDYS%'
            or UPPER(master.description) like '%CARLS%'
            or UPPER(master.description) like '%CHOM%'
            or UPPER(master.description) like '%STREET TACOS%'
            or UPPER(master.description) like '%CAFE TRANG%'
            or UPPER(master.description) like '%PANDA%'
            or UPPER(master.description) like '%KNEADERS%'
            or UPPER(master.description) like '%PANERA%'
            or UPPER(master.description) like '%JCW%'
            or UPPER(master.description) like '%COSTA%'
            or UPPER(master.description) like '%CUBBYS%'
            or UPPER(master.description) like '%MCDONALDS%'
            or UPPER(master.description) like '%MCDONALD''S%'
            or UPPER(master.description) like '%IN N OUT%'
            or UPPER(master.description) like '%PHO PLUS%'
            or UPPER(master.description) like '%SWIG%'
            or UPPER(master.description) like '%PHO THIN%'
            or UPPER(master.description) like '%SONIC%'
            or UPPER(master.description) like '%SUPERFOODS%'
            or UPPER(master.description) like '%MORNING SQUEEZE%'
            or UPPER(master.description) like '%CAFE%'
            or UPPER(master.description) like '%JIMMY JOHNS%'
            or UPPER(master.description) like '%TEXAS ROADHOUSE%'
            or UPPER(master.description) like '%BEANS AND BREWS%'
            or UPPER(master.description) like '%TACOS%'
            or UPPER(master.description) like '%PAPA%'
            or UPPER(master.description) like '%ROXBERRY%'
            or UPPER(master.description) like '%MELTING POT%'
            or UPPER(master.description) like '%BERRY DIVINE%'
            or UPPER(master.description) like '%5GUYS%'
            or UPPER(master.description) like '%FIVE GUYS%'
            or UPPER(master.description) like '%STARBUCKS%'
            or UPPER(master.description) like '%RED ROBIN%'
            or UPPER(master.description) like '%CHIPOTLE%'
            or UPPER(master.description) like '%ALOHA KITCHEN%'
            or UPPER(master.description) like '%FIREHOUSE%'
            or UPPER(master.description) like '%TWO JACKS%'
            or UPPER(master.description) like '%ITALIAN%'
            or UPPER(master.description) like '%PIZZA%'
            or UPPER(master.description) like '%FOOD%'
            or UPPER(master.description) like '%BBQ%'
            or UPPER(master.description) like '%EATERY%'
            or UPPER(master.description) like '%BAKERY%'
            or UPPER(master.description) like '%GRILL%'
            or UPPER(master.description) like '%BREW%'
            or UPPER(master.description) like '%SLAPFISH%'
            or UPPER(master.description) like '%BOWL%'
            or UPPER(master.description) like '%TRADER JOE%'
            or UPPER(master.description) like '%CREAMERY%'
            or UPPER(master.description) like '%BIRDHOUSE%'
            or UPPER(master.description) like '%BURGER%'
            or UPPER(master.description) like '%DONUTS%'
            or UPPER(master.description) like '%THAI%'
            or UPPER(master.description) like '%SUB ZERO%'
            or UPPER(master.description) like '%KITCHE%'
            or UPPER(master.description) like '%ICE CREAM%'
            or UPPER(master.description) like '%BISTRO%'
            or UPPER(master.description) like '%EINSTEIN BAGELS%'
            or UPPER(master.description) like '%CHEESECAKE%'
            or UPPER(master.description) like '%TAQUERIA%'
            or UPPER(master.description) like '%JAMBA JUICE%'
            or UPPER(master.description) like '%BB DINER%'
            or UPPER(master.description) like '%LUNCHBOX%'
            or UPPER(master.description) like '%HARWARD FARMS SWEET%'
            or UPPER(master.description) like '%SNACKS%'
            then 'Fast Food'
        when
            UPPER(master.description) like '%COSTCO GAS%'
            or UPPER(master.description) like '%MAVERIK%'
            or UPPER(master.description) like '%FLYING J%'
            or UPPER(master.description) like '%CHEVRON%'
            or UPPER(master.description) like '%7-ELEVEN%'
            then 'Gas'
        when
            UPPER(master.description) like '%ULTA%'
            or UPPER(master.description) like '%ETSY%'
            or UPPER(master.description) like '%HOME DEPOT%'
            or UPPER(master.description) like '%BATH & BODY%'
            or UPPER(master.description) like '%BARNES & NOBLE%'
            or UPPER(master.description) like '%ACE%'
            or UPPER(master.description) like '%TAILOR%'
            or UPPER(master.description) like '%READY GUNNER%'
            or UPPER(master.description) like '%LOWES%'
            or UPPER(master.description) like '%IKEA%'
            or UPPER(master.description) like '%JOANN%'
            or UPPER(master.description) like '%FORGE JEWELRY%'
            or UPPER(master.description) like '%BEAUTY BY EARTH%'
            or UPPER(master.description) like '%APPLE STORE%'
            or UPPER(master.description) like '%AL\''S%'
            or UPPER(master.description) like '%ZURCHERS%'
            or UPPER(master.description) like '%LEGO%'
            or UPPER(master.description) like '%BABY%'
            or UPPER(master.description) like '%HOME STORE%'
            or UPPER(master.description) like '%HOBBY%'
            or UPPER(master.description) like '%MICHAELS%'
            or UPPER(master.description) like '%HOMEGOODS%'
            or UPPER(master.description) like '%BOUTIQUE%'
            or UPPER(master.description) like '%GUNNIES%'
            or UPPER(master.description) like '%WICK LAB%'
            or UPPER(master.description) like '%BOOK%'
            or UPPER(master.description) like '%TOP GOLF%'
            or UPPER(master.description) like '%STUBHUB%'
            or UPPER(master.description) like '%FEDEX%'
            or UPPER(master.description) like '%USPS%'
            or UPPER(master.description) like '%HALLOWEEN%'
            or UPPER(master.description) like '%NZXT%'
            or UPPER(master.description) like '%STAPLES%'
            or UPPER(master.description) like '%SALT LAKE BEES%'
            or UPPER(master.description) like '%HUNT/FISH%'
            or UPPER(master.description) like '%REPOTME%'
            or UPPER(master.description) like '%TICKETS%'
            or UPPER(master.description) like '%GOFUNDME%'
            or UPPER(master.description) like '%CHARITY%'
            or UPPER(master.description) like '%SILVER SAFARI%'
            or UPPER(master.description) like '%SP STANLEY%'
            or UPPER(master.description) like '%SUN RIVER GARDENS%'
            or UPPER(master.description) like '%BEANYS TO GO VINEYARD%'
            or UPPER(master.description) like '%LDS DIST ONLINE%'
            or UPPER(master.description) like '%CCRI BY U%'
            or UPPER(master.description) like '%UTAHDHA%'
            or UPPER(master.description) like '%BOYCHIK%'
            or UPPER(master.description) like '%SUNOCO%'
            or UPPER(master.description) like '%CINEMARK%'
            or UPPER(master.description) like '%UNIVERSITY MALL%'
            or UPPER(master.description) like '%SEINT 801%'
            or UPPER(master.description) like '%VIVID SEATS%'
            or UPPER(master.description) like '%THE KINLANDS%'
            or UPPER(master.description) like '%CUDDLES RESCUE%'
            or UPPER(master.description) like '%NATIONAL DME%'
            or UPPER(master.description) like '%WICKED CUSHIONS%'
            or UPPER(master.description) like '%DOLLAR TREE%'
            or UPPER(master.description) like '%06/24 DSW%'
            or UPPER(master.description) like '%SMITHBALLPARK%'
            or UPPER(master.description) like '%TICKETMASTER%'
            or UPPER(master.description) like '%OREM SUMMER SN OREM%'
            or UPPER(master.description) like '%SALT LAKE CITY DEP SALT LAKE%'
            or UPPER(master.description) like '%HOGLE ZOO SALT LAKE%'
            or UPPER(master.description) like '%GADGET%'
            or UPPER(master.description) like '%HOME DECOR%'
            then 'Miscellaneous'
        when
            UPPER(master.description) like '%ART SUPPLIES%'
            or UPPER(master.description) like '%MOVIE%'
            or UPPER(master.description) like '%SNOWBOARD%'
            or UPPER(master.description) like '%COOKING CLASS%'
            or UPPER(master.description) like '%CELEBRATION%'
            or UPPER(master.description) like '%CRAFT SUPPLIES%'
            or UPPER(master.description) like '%OUTDOOR EQUIPMENT%'
            or UPPER(master.description) like '%HIKING GEAR%'
            or UPPER(master.description) like '%ART EXHIB%'
            or UPPER(master.description) like '%APPLE ORCHARD%'
            or UPPER(master.description) like '%PUMPKIN PATCH%'
            then 'Entertainment'
        when
            UPPER(master.description) like '%QUICKQUACK%'
            or UPPER(master.description) like '%AUTO PARTS%'
            or UPPER(master.description) like '%AUTOZONE%'
            or UPPER(master.description) like '%JIFFY LUBE%'
            or UPPER(master.description) like '%O\''REILLY%'
            or UPPER(master.description) like '%DMV%'
            or UPPER(master.description) like '%LES SCHWAB%'
            or UPPER(master.description) like '%CLEGG AUTO%'
            or UPPER(master.description) like '%DMV%'
            or UPPER(master.description) like '%DRIVER%'
            or UPPER(master.description) like '%PARKING%'
            or UPPER(master.description) like '%AUTOGLASS%'
            or UPPER(master.description) like '%CAR WASH%'
            then 'Cars'
        when
            UPPER(master.description) like '%TARGET%'
            or UPPER(master.description) like '%NIKE%'
            or UPPER(master.description) like '%AMERICAN EAGLE%'
            or UPPER(master.description) like '%TARGET%'
            or UPPER(master.description) like '%NORDRACK%'
            or UPPER(master.description) like '%COLEHAAN%'
            or UPPER(master.description) like '%BUCKLE%'
            or UPPER(master.description) like '%AE OUT%'
            or UPPER(master.description) like '%COTTON ON%'
            or UPPER(master.description) like '%ALBION%'
            or UPPER(master.description) like '%GAP%'
            or UPPER(master.description) like '%BOHME%'
            or UPPER(master.description) like '%SEPHORA%'
            or UPPER(master.description) like '%H&M%'
            or UPPER(master.description) like '%TIMBERLAND%'
            or UPPER(master.description) like '%BYLT%'
            or UPPER(master.description) like '%NORDSTROM%'
            or UPPER(master.description) like '%KIZIK%'
            or UPPER(master.description) like '%BRONXTON%'
            or UPPER(master.description) like '%QUIKSILVER%'
            or UPPER(master.description) like '%ADIDAS%'
            or UPPER(master.description) like '%QUIKSILVER%'
            or UPPER(master.description) like '%DOWNEAST%'
            or UPPER(master.description) like '%VANS%'
            or UPPER(master.description) like '%OLD NAVY%'
            or UPPER(master.description) like '%CLAIRE%'
            or UPPER(master.description) like '%COLE HAAN%'
            or UPPER(master.description) like '%LULULEMON%'
            or UPPER(master.description) like '%SHOP STEVIE%'
            or UPPER(master.description) like '%LOVE OLIVE CO%'
            or UPPER(master.description) like '%UPTOWN CHEAPSKATE%'
            or UPPER(master.description) like '%LIVY&KATE%'
            or UPPER(master.description) like '%CLOTHIN%'
            or UPPER(master.description) like '%MENTIONABLES%'
            or UPPER(master.description) like '%UNDER ARMOUR%'
            or UPPER(master.description) like '%BARBELL%'
            or UPPER(master.description) like '%FACTORY OUTLET%'
            or UPPER(master.description) like '%MIKAROSE%'
            or UPPER(master.description) like '%CONVERSE%'
            or UPPER(master.description) like '%BRAXLEY BANDS%'
            or UPPER(master.description) like '%HALFTEES%'
            or UPPER(master.description) like '%LENIN RM LLC%'
            or UPPER(master.description) like '%PUBLIX%'
            or UPPER(master.description) like '%MADEBYMARY%'
            or UPPER(master.description) like '%THE SOCK DRAWER%'
            then 'Clothes'
        when
            UPPER(master.description) like '%COLLEGE%'
            or UPPER(master.description) like '%STUDENT%'
            or UPPER(master.description) like '%UDEMY%'
            or UPPER(master.description) like '%CHECK #%'
            or UPPER(master.description) like '%WESTERN REGIONAL EXAM%'
            or UPPER(master.description) like '%PREP BLAST%'
            then 'School'
        when
            UPPER(master.description) like '%AMERICAN AIR%'
            or UPPER(master.description) like '%VRBO%'
            or UPPER(master.description) like '%DELTA%'
            or UPPER(master.description) like '%HERTZ%'
            or UPPER(master.description) like '%HOTEL%'
            or UPPER(master.description) like '%ROYAL CARIBBEAN%'
            or UPPER(master.description) like '%SEAS%'
            or UPPER(master.description) like '%UBER%'
            or UPPER(master.description) like '%AIRBNB%'
            or UPPER(master.description) like '%VACATION%'
            or UPPER(master.description) like '%INN%'
            or UPPER(master.description) like '%ALASKA%'
            or UPPER(master.description) like '%AIRPORT%'
            or UPPER(master.description) like '%ATLANTA%'
            or UPPER(master.description) like '%SAVANNAH%'
            or UPPER(master.description) like '%MARRIOTT%'
            or UPPER(master.description) like '%CHARLESTON%'
            or UPPER(master.description) like '%TYBEE ISLAND%'
            or UPPER(master.description) like '%ISLE OF PALMS%'
            or UPPER(master.description) like '%SOUTHWES%'
            or (
                UPPER(master.description) like '%RENT%'
                and UPPER(master.description) like '%CAR%'
            )
            then 'Travel'
        when
            UPPER(master.description) like '%PROVO SPORTS%'
            or UPPER(master.description) like '%WALGREENS%'
            or UPPER(master.description) like '%REVEREHEALTH%'
            or UPPER(master.description) like '%HUNNY B%'
            or UPPER(master.description) like '%SALON%'
            or UPPER(master.description) like '%OLAPLEX%'
            or UPPER(master.description) like '%HUNNY B%'
            or UPPER(master.description) like '%HAIR%'
            or UPPER(master.description) like '%UVEC - CONTACTS%'
            or UPPER(master.description) like '%PHARMACY%'
            or UPPER(master.description) like '%CVS%'
            or UPPER(master.description) like '%MEDIC%'
            or UPPER(master.description) like '%BEAUTY%'
            or UPPER(master.description) like '%PROVO REC%'
            or UPPER(master.description) like '%UVEC%'
            or UPPER(master.description) like '%CHIRO%'
            or UPPER(master.description) like '%EYE%'
            or UPPER(master.description) like '%INTERMOUNTAIN%'
            or UPPER(master.description) like '%HYPERICE%'
            or UPPER(master.description) like '%SKINCARE%'
            or UPPER(master.description) like '%ROSENBERG COOLEY%'
            or UPPER(master.description) like '%INSTACARE%'
            or UPPER(master.description) like '%NAILS%'
            or UPPER(master.description) like '%PAUL MITCHELL%'
            or UPPER(master.description) like '%LOREAL%'
            or UPPER(master.description) like '%SPA DAY%'
            or UPPER(master.description) like '%SPA AND WELLNESS%'
            or UPPER(master.description) like '%SPA TREATMENT%'
            or UPPER(master.description) like '%FITNESS%'
            then 'Health'
        when
            UPPER(master.description) like '%.COM%'
            or UPPER(master.description) like '%AMZN%'
            or UPPER(master.description) like '%COSTCO COM%'
            then 'Web Purchase'
        when
            UPPER(master.description) like 'ONLINE PAYMENT, THANK YOU%'
            or UPPER(master.description) like 'ONLINE TRANSFER TO WRIGHT%'
            or UPPER(master.description) like 'ONLINE TRANSFER FROM WRIGHT%'
            or UPPER(master.description) like 'AUTOPAY 211%'
            or UPPER(master.description) like 'PAYMENT THANK YOU%'
            then 'Credit Card Payments'
        else 'Unknown'
    end as transaction_category

from personal_finance.my_finances.transformed_historical master -- This is uploaded

order by
    master.date asc;
